#! /usr/bin/env bash

if [ -d ~/.rbenv ] ; then
  echo 'rbenv is installed.'
else
  git clone https://github.com/sstephenson/rbenv.git      ~/.rbenv
  git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build

  echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
  echo 'eval "$(rbenv init -)"'               >> ~/.bash_profile
  echo ''                                     >> ~/.bash_profile
fi

